name: Self Report

on:
  schedule:
    - cron: "30 22,4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v1"
        with:
          config_file: .github/vpn/config.ovpn
          username: $(cut -d',' -f1 <<< $(cut -d';' -f1 <<< $users))
          password: $(cut -d',' -f2 <<< $(cut -d';' -f1 <<< $users))
      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: until ping -c1 xk.autoisp.shu.edu.cn; do sleep 2; done
      - name: Report Start
        env:
          users: ${{ secrets.USERS }}
          send: ${{ secrets.SEND }}
        run: "python main.py gh"